### ISSUE TITLE
Calling Azure related cmdlets

### ISSUE THREAD

**Issue by eosfor** [powercode/PSParallel#1] opened 2015-11-24 12:54 UTC
Hi Staffan

You are doing really cool thing. It is overwhelmingly helpful in many cases! Thank you!

But there is one case where i failed to use it. I was trying to call [this](https://eosfor.wordpress.com/2015/11/02/how-to-search-for-object-in-azure/) from invoke-parallel and it failed. Perhaps the issue is with auto loading of the module or something. Did you ever checked Azure cmdlets to run in parallel? Is it possible to "clone" current runspace to avoid all of those issues with auto loading?

Error messages were like:

Invoke-Parallel : The 'Get-AzureSubscription' command was found in the module 'Azure', but the module could not be loaded. For more information, run 'Import-Module Azure'.
At line:1 char:16
+ $s[100..120] | Invoke-Parallel {
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureSubscription:String) [Invoke-Parallel], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,PSParallel.InvokeParallelCommand

....

Invoke-Parallel : ResourceNotFound: The operation request ID was not found.
At line:1 char:16
+ $s[100..120] | Invoke-Parallel {
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], CloudException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand

**Comment by eosfor** [comment] 2015-11-24 14:01
Here is the stack of errors i've got

Invoke-Parallel : ResourceNotFound: The operation request ID was not found.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], CloudException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : ResourceNotFound: The operation request ID was not found.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], CloudException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Collection was modified; enumeration operation may not execute.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], InvalidOperationException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : ResourceNotFound: The operation request ID was not found.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], CloudException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Collection was modified; enumeration operation may not execute.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], InvalidOperationException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : {"error":{"code":"InvalidSubscriptions","message":"Subscription identifier cannot be an empty string"}}
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-Parallel], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,PSParallel.InvokeParallelCommand
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Index was outside the bounds of the array.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : ResourceNotFound: The operation request ID was not found.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-Parallel], CloudException
    + FullyQualifiedErrorId : PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel {
+          ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand

**Comment by powercode** [comment] 2015-11-24 14:33
Unfortunately, I haven't used any azure stuff at all.
In v1.7, however, there is an -InitialSessionSpace parameter, where you can specify the ISS to use.

It would be interesting to see if you can configure a sessionspace that works that way.
You could try something like the following:

$iss = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
$iss.ImportPSModule("Azure")
... | Invoke-Parallel -InitialSessionState $iss {..}

**Comment by powercode** [comment] 2015-11-24 14:37
I am also a bit unclear on what you actually were trying to execute. Can you provide the full commandline that you were trying to execute?

**Comment by eosfor** [comment] 2015-11-24 14:49
Here is the "script"

$s = Get-MKTVm -Detailed -ErrorVariable failedHosts
$failedHosts.TargetObject.RequestUri.absoluteuri

$size = $s.Count
$i = 0

$iss = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
$iss.ImportPSModule("Azure")
$iss.ImportPSModule("wk-gss")

$details = 
    $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
    #$i += 1
    #Write-Progress -Activity "Matching in progress" -PercentComplete (($i/$size)*100) -CurrentOperation "Getting Azure object"
    $vm =  Get-AzureObject -Name $_.assetName -VMOnly
    $_ | select cmAssetId, assetName, 
                service, isServiceActive, 
                serviceStartDate, serviceEndDate, 
                lastActivityDate, assetDiscoveredDate, 
                isDiscovered, lastKnownState, 
                locationCode, locationName, 
                initialOrderId, initialOrderSubmitter,
                @{l = 'MKTNetworks'; e = {$_.cmresourcegroup.network.subnets.providerIdentifier}},
                @{l = 'AZSubscriptionName'; e = {$vm.SubscriptionName}},
                @{l = 'ServiceName'; e = {$vm.ServiceName}},
                @{l = 'Name'; e = {$vm.Name}},
                @{l = 'PowerState'; e = {$vm.PowerState}},
                @{l = 'Status'; e = {$vm.Status}},
                @{l = 'OSType'; e = {$vm.vm.OSVirtualHardDisk.OS}},
                @{l = 'VirtualNetworkName'; e = {$vm.VirtualNetworkName}},
                @{l = 'AzureSubnet'; e = {$vm.AzureSubnet}},
                @{l = 'IpAddress'; e = {$vm.IpAddress}},
                @{l = 'StaticIpAddress'; e = {$vm.StaticIpAddress}},
                href

    }

and here what i've got now

Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Index was outside the bounds of the array.
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : {"error":{"code":"InvalidSubscriptions","message":"Subscription identifier cannot be an empty string"}}
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-Parallel], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,PSParallel.InvokeParallelCommand
Invoke-Parallel : {"error":{"code":"InvalidSubscriptions","message":"Subscription identifier cannot be an empty string"}}
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-Parallel], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,PSParallel.InvokeParallelCommand
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:2 char:10
+     $s | Invoke-Parallel -InitialSessionState $iss -ScriptBlock {
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand

and so on

**Comment by eosfor** [comment] 2015-11-24 14:53
Is it possible to invoke come command in that "sessionstate" and then reuse it. For instance i'd try calling add-azureaccount in it ad then pass it to Invoke-Parallel

**Comment by powercode** [comment] 2015-11-24 14:55
You can add variables to the iss.

**Comment by powercode** [comment] 2015-11-24 14:58
```PowerShell
$iss = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
$iss.ImportPSModule("Azure")
$varEntry = [System.Management.Automation.Runspaces.SessionStateVariableEntry]::new('SomeVar', 'SomeValue', 'somedescription')
$iss.Variables.Add($varEntry)
... | Invoke-Parallel -InitialSessionState $iss {..}
```

**Comment by eosfor** [comment] 2015-11-24 14:59
well, the problem is that add-azureaccount creates some hidden stuff in memory and when invoked it asks for credentials

**Comment by eosfor** [comment] 2015-11-24 15:04
i did another test just now

$iss = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
$iss.ImportPSModule("Azure")
$iss.ImportPSModule("wk-gss")

1..2 | Invoke-Parallel -InitialSessionState $iss -ScriptBlock { get-azuresubscription }

returns the following

SubscriptionName        SubscriptionId                       IsCurrent IsDefault
----------------        --------------                       --------- ---------
somth1			        bec19ae6-3c1b-4bb5-b2b1-ff432a4101f0 False     False    
somth2			        ee2c05db-ecf5-4710-bef6-4d59794c55aa False     False    
somth3			        0b51f17c-7513-46c2-9d9d-a709f9117ba9 False     False    
somth4			        22c41a05-b789-4b27-bfcd-bdc19efbc413 False     False    
somth5			        387793bd-6e1e-4893-a551-aa6c032f7aac False     False    
somth6			        20d52582-3ffc-4e71-a175-6d3b672072cd True      True     
somth7			        98c9f0e0-1612-4a5f-a577-7d0867d3e1d7 False     False    
somth8			        c3121082-3c45-4247-be7a-ae89b0b39e18 False     False    
somth9			        baa21b36-a672-4347-b7ea-2bad7f2d31a8 False     False    
Invoke-Parallel : Array dimensions exceeded supported range.
At line:1 char:8
+ 1..2 | Invoke-Parallel -InitialSessionState $iss -ScriptBlock { get-a ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
Invoke-Parallel : Array dimensions exceeded supported range.
At line:1 char:8
+ 1..2 | Invoke-Parallel -InitialSessionState $iss -ScriptBlock { get-a ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Parallel], OverflowException
    + FullyQualifiedErrorId : System.OverflowException,PSParallel.InvokeParallelCommand
 
somth1			        bec19ae6-3c1b-4bb5-b2b1-ff432a4101f0 False     False    
somth2			        ee2c05db-ecf5-4710-bef6-4d59794c55aa False     False    
somth3			        0b51f17c-7513-46c2-9d9d-a709f9117ba9 False     False    
somth4			        22c41a05-b789-4b27-bfcd-bdc19efbc413 False     False    
somth5			        387793bd-6e1e-4893-a551-aa6c032f7aac False     False    
somth6			        20d52582-3ffc-4e71-a175-6d3b672072cd True      True     
somth7			        98c9f0e0-1612-4a5f-a577-7d0867d3e1d7 False     False    
somth8			        c3121082-3c45-4247-be7a-ae89b0b39e18 False     False    
somth9			        baa21b36-a672-4347-b7ea-2bad7f2d31a8 False     False

**Comment by eosfor** [comment] 2015-11-24 15:08
can we just have a quick skype chat? or even call? )

**Comment by powercode** [comment] 2015-11-24 15:21
Cant talk.
What version are you running?
Please make sure you are at least running v1.7.

**Comment by eosfor** [comment] 2015-11-24 15:24
yep. it is 1.7

**Comment by powercode** [comment] 2015-11-24 15:30
It may also be the case that the cmdlets you call are not designed to be run in parallel. If they share state like you say it is hard to tell what is happening.
$error[0].Exception.StackTrace may also give a better understanding of where things go wrong

**Comment by eosfor** [comment] 2015-11-24 15:37
PS C:\Windows\system32> $error[0].Exception.StackTrace
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Common.Authentication.Models.JsonProfileSerializer.Serialize(AzureProfile profile)
   at Microsoft.Azure.Common.Authentication.Models.AzureProfile.Save(String path)
   at Microsoft.WindowsAzure.Commands.Utilities.Profile.SubscriptionCmdletBase.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by eosfor** [comment] 2015-11-24 15:39
Is it possible to reuse current runspace instead of creating new one?

**Comment by powercode** [comment] 2015-11-24 15:41
It seems something goes wrong in the azure cmdlets. They may very well not be designed to be run in parallel. 
Invoke-Parallel is a somewhat dangerous tool. It's primary target was to run native longrunning executables in parallel.

An no, it always creates a new PowerShell, but it reuses runspaces in a pool. You have the source code :)

**Comment by powercode** [comment] 2015-11-24 17:31
I'm closing this issue as by design. 
It is a good feature though to be able to reuse runspaces.

**Closed by powercode** 2015-11-24 17:31 UTC
